### ISSUE TITLE
如何升级到支持2.XX版本？

### ISSUE THREAD

**Issue by dogagithub** [kbengine/kbengine_js_plugins#40]
服务端想用组件开发，这个客户端是1.3.12的。请问需要怎样才能支持新版本服务端？

**Comment by kebiao** [comment]
估计不懂得话比较难。  最好全部升级

**Comment by dogagithub** [comment]
怎样全部升级？因为我们开发引擎用的是cocos creator，有可用的2版本以上的js客户端版本么？

**Comment by kebiao** [comment]
论坛上有别人写的js支持2,x版本， 可以找找看

**Comment by kebiao** [comment]
github也可以找找看
